<?php

namespace App\Nova\Dashboards;

use App\Nova\Metrics\TotalAreasCount;
use App\Nova\Metrics\TotalProvincesCount;
use App\Nova\Metrics\TotalRegionsCount;
use App\Nova\Metrics\TotalSectorsCount;
use Laravel\Nova\Dashboard;

class ItalyDashboard extends Dashboard
{

    public static function label()
    {
        return 'Riepilogo nazionale'; // TODO: Change the autogenerated stub
    }

    /**
     * Get the cards for the dashboard.
     *
     * @return array
     */
    public function cards()
    {
        return [
            (new TotalRegionsCount())->width('1/4'),
            (new TotalProvincesCount())->width('1/4'),
            (new TotalAreasCount())->width('1/4'),
            (new TotalSectorsCount())->width('1/4'),
        ];
    }

    /**
     * Get the URI key for the dashboard.
     *
     * @return string
     */
    public static function uriKey()
    {
        return 'italy-dashboard';
    }
}
