<?php

namespace App\Nova\Dashboards;

use App\Nova\Metrics\TotalAreasCount;
use App\Nova\Metrics\TotalProvincesCount;
use App\Nova\Metrics\TotalRegionsCount;
use App\Nova\Metrics\TotalSectorsCount;
use Ericlagarda\NovaTextCard\TextCard;
use Illuminate\Support\Facades\DB;
use Laravel\Nova\Dashboard;

class ItalyDashboard extends Dashboard
{

    public static function label()
    {
        return 'Riepilogo nazionale'; // TODO: Change the autogenerated stub
    }

    /**
     * Get the cards for the dashboard.
     *
     * @return array
     */
    public function cards()
    {

        $values = DB::table('hiking_routes')
            ->select('osm2cai_status', DB::raw('count(*) as num'))
            ->groupBy('osm2cai_status')
            ->get();

        $numbers = [];
        $numbers[1] = 0;
        $numbers[2] = 0;
        $numbers[3] = 0;
        $numbers[4] = 0;

        if (count($values) > 0) {
            foreach ($values as $value) {
                $numbers[$value->osm2cai_status] = $value->num;
            }
        }

        $tot = array_sum($numbers) - $numbers[0];

        return [
            (new TotalProvincesCount())->width('1/4'),
            (new TotalAreasCount())->width('1/4'),
            (new TotalSectorsCount())->width('1/4'),
            (new TextCard())->width('1/4')->text('#tot')->heading($tot),

            (new TextCard())->width('1/4')
                ->text('#sda 1')->heading('<div style="background-color: #F7CA16; color: white; font-size: xx-large">' . $numbers[1] . '</div>')->headingAsHtml(),
            (new TextCard())->width('1/4')
                ->text('#sda 2')->heading('<div style="background-color: #F7A117; color: white; font-size: xx-large">' . $numbers[2] . '</div>')->headingAsHtml(),
            (new TextCard())->width('1/4')
                ->text('#sda 3')->heading('<div style="background-color: #F36E45; color: white; font-size: xx-large">' . $numbers[3] . '</div>')->headingAsHtml(),
            (new TextCard())->width('1/4')
                ->text('#sda 4')->heading('<div style="background-color: #47AC34; color: white; font-size: xx-large">' . $numbers[4] . '</div>')->headingAsHtml(),

        ];
    }

    /**
     * Get the URI key for the dashboard.
     *
     * @return string
     */
    public static function uriKey()
    {
        return 'italy-dashboard';
    }
}
